### ISSUE TITLE
Dunst to show notifications on volume and brightness change

### ISSUE THREAD

**Issue by hg8** [kelp/arch#3]
Hello,
First of all thanks for your guide, it came useful.

I saw in your TODO that you wanted a way to setup Dunst to show notifications on volume and brightness change. 
Here are my scripts to do so if you are still interested in achieving this. 

[brightness](https://github.com/hg8/dotfiles/blob/master/bin/brightness) 
![2019-05-22-082913_373x102_scrot](https://user-images.githubusercontent.com/9076747/58159341-cf227e80-7c6b-11e9-90b0-59f394ac3e93.png)

[volume](https://github.com/hg8/dotfiles/blob/master/bin/volume) 
![2019-05-22-082926_356x102_scrot](https://user-images.githubusercontent.com/9076747/58159343-cfbb1500-7c6b-11e9-9aad-7d8ba1d858b9.png)

**Comment by kelp** [comment]
Thanks for the suggestion! I'll play around with that soon and see about integrating it into my howto.
